### ISSUE TITLE
Eliminare riferimento alla data

### ISSUE THREAD

**Issue by mattmezza** [myunimol/iOS#24]
Come da immagine, eliminare riferimento alla data, lasciare solo l'orario.

![simulator screen shot oct 31 2016 5 11 59 pm](https://cloud.githubusercontent.com/assets/1915989/19861539/34790e3e-9f8d-11e6-8e49-7ce16c1104b4.png)

**Comment by giograno** [comment]
The project is going to be archived. I am therefore closing this issue.
